git:
  depth: 10
  quiet: false
language: java
addons:
  chrome: stable
jdk:
  - oraclejdk8
script:
  - mkdir drivers
  - cd drivers
  - wget "https://chromedriver.storage.googleapis.com/73.0.3683.68/chromedriver_linux64.zip"
  - unzip *.zip -d .
  - mvn clean verify -Dtest=TestRunner -DdriverLocation=drivers -DchromeDriverBinary=chromedriver.bin

# safelist
branches:
  only:
    - master



