git:
  depth: 10
  quiet: false
language: java
addons:
  chrome: stable
before_script:
  - chromedriver-update 73.0.3683.68
script:
  - mkdir drivers
  - cd drivers
  - wget "https://chromedriver.storage.googleapis.com/77.0.3865.40/chromedriver_linux64.zip"
  - unzip *.zip -d .
  - cd /home/travis/build/quixoticmonk/SeleniumCucumberDemo
  - mvn clean verify -Dtest=TestRunner -DdriverLocation=drivers -DchromeDriverBinary=chromedriver -DheadlessChrome=true

# safelist
branches:
  only:
    - master
